<?php
return [
	'admin_email' => env('ADMIN_EMAIL'),
	'profile_image_url' => "/upload/profile/",
	'cms_page_url' => "/upload/pages/",
	'blog_url' => "/upload/blogs/",
	'temp_file_url' => "/upload/temp/",
	'building_images_url' => "/upload/building_images/",
	'land_images_url' => "/upload/land_images/",
	'construction_images_url' => "/upload/construction_images/",
	'tp_images_url' => "/upload/tp_images/",

	'property_configuration' => [
		'1' => 'office space',
		'2' => 'Co-working',
		'3' => 'Ground floor',
		'4' => '1st floor',
		'5' => '2nd floor',
		'6' => '3rd floor',
		'7' => 'Warehouse',
		'8' => 'Cold Storage',
		'9' => 'ind. shed',
		'10' => 'Commercial Land',
		'11' => 'Agricultural/Farm Land',
		'12' => 'Industrial Land',
		'13' => '1 rk',
		'14' => '1bhk',
		'15' => '2bhk',
		'16' => '3bhk',
		'17' => '4bhk',
		'18' => '5bhk',
		'19' => '5+bhk',
		'20' => 'Plotting',
		'21' => '1Bed',
		'22' => '2Bed',
		'23' => '3Bed',
		'24' => '4Bed',
		'25' => '4+Bed',
	]

];
